# Generated by Django 6.0.6 on 2026-09-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedBotIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Honeypot Triggered', max_length=255)),
            ],
        ),
    ]
