"""
Django settings for Invictus project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ROOT_DIR = BASE_DIR.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qzv25z)vyf3q142l0##gf^v75wz6$c1z*(mir^k@6$x+6yt!^r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_vite',

    "polls.apps.PollsConfig",
    'api',
    'blog',
    'users',
    'analytics',

    'rest_framework',
    'corsheaders',

    'crispy_forms',
    'tinymce',
    'crispy_bootstrap5',
    'django_browser_reload',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',        #CORS Headers Middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'django_browser_reload.middleware.BrowserReloadMiddleware',  # Browser Reload Middleware

    # Add your custom middleware here (format: 'app_name.file_name.ClassClassName')
    'analytics.middleware.TrafficLoggerMiddleware', 
    ]

#ROOT_URLCONF = 'Invictus.urls'



# 🛠️ Django-Vite Configurations
DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
        "dev_server_host": "localhost",
        "dev_server_port": 3000,
        # FIX: Explicitly supply the Vite server URL as the static prefix during dev
        "static_url_prefix": "http://localhost:3000" if DEBUG else "", 
        "manifest_path": ROOT_DIR / "static" / "dist" / ".vite" / "manifest.json",
        }
    }


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
    #    'rest_framework.authentication.SessionAuthentication',
    #    'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

ROOT_URLCONF = 'Invictus.urls'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256'
}
# 1. Allow CORS requests
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # Use this if using Create-React-App
    "http://127.0.0.1:3000",
    "http://localhost:5173", # Use this if using Vite
]
# CORS_ORIGIN_ALLOW_ALL = True
# Permit cookies to be passed along with cross-origin requests
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = (
    "DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT", "REGISTER",
)

# 2. Tell Django's CSRF middleware to trust your React frontend
# Note: Django requires the protocol (http://) included here
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
# Ensure the CSRF cookie isn't strictly locked out of cross-site scenarios during dev
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Optional for development: If React is HTTP and Django is HTTP, keep secure False
CSRF_COOKIE_SECURE = False 
SESSION_COOKIE_SECURE = False

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

#TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ['127.0.0.1', "localhost"]
NPM_BIN_PATH = "/home/kumar/.local/bin/npm"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ROOT_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Invictus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        #'NAME' : os.getenv("DB_NAME"),
        #'USER' : os.getenv("DB_USER"),
        #'PASSWORD' : os.getenv("DB_PWD"),
        #'HOST': os.getenv("DB_HOST"),
        #'PORT' : os.getenv("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL ='login'
LOGIN_REDIRECT_URL = 'dashboard'
# Redirect to the login page after logout
LOGOUT_REDIRECT_URL = 'login'  

# OR redirect to the home/landing page
# LOGOUT_REDIRECT_URL = '/'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ 
    ROOT_DIR / "static", 
    ROOT_DIR / "frontend",
    ROOT_DIR / "static/dist",] # Directory where Django looks for global assets

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR.parent, 'media')  # Directory where uploaded media files

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
